/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using WhatsAPI.Client;
using WhatsAPI.models;

namespace WhatsAPI.whatsapi
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInstanceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a new instance key.
        /// </summary>
        /// <remarks>
        /// This endpoint is used to create a new WhatsApp Web instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesCreateGet (string instanceKey = default(string));

        /// <summary>
        /// Creates a new instance key.
        /// </summary>
        /// <remarks>
        /// This endpoint is used to create a new WhatsApp Web instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesCreateGetWithHttpInfo (string instanceKey = default(string));
        /// <summary>
        /// Get contacts.
        /// </summary>
        /// <remarks>
        /// Fetches the list of contacts in the instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyContactsGet (string instanceKey);

        /// <summary>
        /// Get contacts.
        /// </summary>
        /// <remarks>
        /// Fetches the list of contacts in the instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyContactsGetWithHttpInfo (string instanceKey);
        /// <summary>
        /// Delete Instance.
        /// </summary>
        /// <remarks>
        /// Deletes the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyDeleteDelete (string instanceKey);

        /// <summary>
        /// Delete Instance.
        /// </summary>
        /// <remarks>
        /// Deletes the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyDeleteDeleteWithHttpInfo (string instanceKey);
        /// <summary>
        /// Get Instance.
        /// </summary>
        /// <remarks>
        /// Returns the instance data of single instance with connection status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyGet (string instanceKey);

        /// <summary>
        /// Get Instance.
        /// </summary>
        /// <remarks>
        /// Returns the instance data of single instance with connection status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyGetWithHttpInfo (string instanceKey);
        /// <summary>
        /// Logout Instance.
        /// </summary>
        /// <remarks>
        /// Logouts of the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyLogoutDelete (string instanceKey);

        /// <summary>
        /// Logout Instance.
        /// </summary>
        /// <remarks>
        /// Logouts of the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyLogoutDeleteWithHttpInfo (string instanceKey);
        /// <summary>
        /// Get QrCode.
        /// </summary>
        /// <remarks>
        /// Returns the qrcode in the base64 format.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyQrcodeGet (string instanceKey);

        /// <summary>
        /// Get QrCode.
        /// </summary>
        /// <remarks>
        /// Returns the qrcode in the base64 format.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyQrcodeGetWithHttpInfo (string instanceKey);
        /// <summary>
        /// Change Webhook url.
        /// </summary>
        /// <remarks>
        /// Changes the webhook url of an instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesInstanceKeyWebhookPut (string instanceKey, StructsWebhookPayload data);

        /// <summary>
        /// Change Webhook url.
        /// </summary>
        /// <remarks>
        /// Changes the webhook url of an instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesInstanceKeyWebhookPutWithHttpInfo (string instanceKey, StructsWebhookPayload data);
        /// <summary>
        /// Get all instances.
        /// </summary>
        /// <remarks>
        /// Fetches the list of all Instances with login status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MainAPIResponse</returns>
        MainAPIResponse InstancesListGet ();

        /// <summary>
        /// Get all instances.
        /// </summary>
        /// <remarks>
        /// Fetches the list of all Instances with login status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        ApiResponse<MainAPIResponse> InstancesListGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Creates a new instance key.
        /// </summary>
        /// <remarks>
        /// This endpoint is used to create a new WhatsApp Web instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesCreateGetAsync (string instanceKey = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Creates a new instance key.
        /// </summary>
        /// <remarks>
        /// This endpoint is used to create a new WhatsApp Web instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesCreateGetWithHttpInfoAsync (string instanceKey = default(string), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get contacts.
        /// </summary>
        /// <remarks>
        /// Fetches the list of contacts in the instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyContactsGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get contacts.
        /// </summary>
        /// <remarks>
        /// Fetches the list of contacts in the instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyContactsGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Delete Instance.
        /// </summary>
        /// <remarks>
        /// Deletes the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyDeleteDeleteAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete Instance.
        /// </summary>
        /// <remarks>
        /// Deletes the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyDeleteDeleteWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get Instance.
        /// </summary>
        /// <remarks>
        /// Returns the instance data of single instance with connection status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Instance.
        /// </summary>
        /// <remarks>
        /// Returns the instance data of single instance with connection status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Logout Instance.
        /// </summary>
        /// <remarks>
        /// Logouts of the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyLogoutDeleteAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Logout Instance.
        /// </summary>
        /// <remarks>
        /// Logouts of the instance with the provided key.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyLogoutDeleteWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get QrCode.
        /// </summary>
        /// <remarks>
        /// Returns the qrcode in the base64 format.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyQrcodeGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get QrCode.
        /// </summary>
        /// <remarks>
        /// Returns the qrcode in the base64 format.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyQrcodeGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Change Webhook url.
        /// </summary>
        /// <remarks>
        /// Changes the webhook url of an instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyWebhookPutAsync (string instanceKey, StructsWebhookPayload data, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Change Webhook url.
        /// </summary>
        /// <remarks>
        /// Changes the webhook url of an instance.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyWebhookPutWithHttpInfoAsync (string instanceKey, StructsWebhookPayload data, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get all instances.
        /// </summary>
        /// <remarks>
        /// Fetches the list of all Instances with login status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        System.Threading.Tasks.Task<MainAPIResponse> InstancesListGetAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get all instances.
        /// </summary>
        /// <remarks>
        /// Fetches the list of all Instances with login status.
        /// </remarks>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesListGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InstanceApi : IInstanceApi
    {
        private WhatsAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InstanceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InstanceApi(String basePath)
        {
            this.Configuration = new WhatsAPI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = WhatsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstanceApi"/> class
        /// </summary>
        /// <returns></returns>
        public InstanceApi()
        {
            this.Configuration = WhatsAPI.Client.Configuration.Default;

            ExceptionFactory = WhatsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstanceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public InstanceApi(WhatsAPI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = WhatsAPI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = WhatsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public WhatsAPI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public WhatsAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Creates a new instance key. This endpoint is used to create a new WhatsApp Web instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesCreateGet (string instanceKey = default(string))
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesCreateGetWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new instance key. This endpoint is used to create a new WhatsApp Web instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesCreateGetWithHttpInfo (string instanceKey = default(string))
        {

            var localVarPath = "/instances/create";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "instance_key", instanceKey)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesCreateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Creates a new instance key. This endpoint is used to create a new WhatsApp Web instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesCreateGetAsync (string instanceKey = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesCreateGetWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a new instance key. This endpoint is used to create a new WhatsApp Web instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Insert instance key if you want to provide custom key (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesCreateGetWithHttpInfoAsync (string instanceKey = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/instances/create";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "instance_key", instanceKey)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesCreateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get contacts. Fetches the list of contacts in the instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyContactsGet (string instanceKey)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyContactsGetWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get contacts. Fetches the list of contacts in the instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyContactsGetWithHttpInfo (string instanceKey)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyContactsGet");

            var localVarPath = "/instances/{instance_key}/contacts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyContactsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get contacts. Fetches the list of contacts in the instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyContactsGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyContactsGetWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get contacts. Fetches the list of contacts in the instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyContactsGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyContactsGet");

            var localVarPath = "/instances/{instance_key}/contacts";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyContactsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Delete Instance. Deletes the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyDeleteDelete (string instanceKey)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyDeleteDeleteWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Instance. Deletes the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyDeleteDeleteWithHttpInfo (string instanceKey)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyDeleteDelete");

            var localVarPath = "/instances/{instance_key}/delete";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyDeleteDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Delete Instance. Deletes the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyDeleteDeleteAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyDeleteDeleteWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete Instance. Deletes the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyDeleteDeleteWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyDeleteDelete");

            var localVarPath = "/instances/{instance_key}/delete";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyDeleteDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get Instance. Returns the instance data of single instance with connection status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyGet (string instanceKey)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyGetWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Instance. Returns the instance data of single instance with connection status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyGetWithHttpInfo (string instanceKey)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyGet");

            var localVarPath = "/instances/{instance_key}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get Instance. Returns the instance data of single instance with connection status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyGetWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Instance. Returns the instance data of single instance with connection status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyGet");

            var localVarPath = "/instances/{instance_key}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Logout Instance. Logouts of the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyLogoutDelete (string instanceKey)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyLogoutDeleteWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Logout Instance. Logouts of the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyLogoutDeleteWithHttpInfo (string instanceKey)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyLogoutDelete");

            var localVarPath = "/instances/{instance_key}/logout";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyLogoutDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Logout Instance. Logouts of the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyLogoutDeleteAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyLogoutDeleteWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Logout Instance. Logouts of the instance with the provided key.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyLogoutDeleteWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyLogoutDelete");

            var localVarPath = "/instances/{instance_key}/logout";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyLogoutDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get QrCode. Returns the qrcode in the base64 format.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyQrcodeGet (string instanceKey)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyQrcodeGetWithHttpInfo(instanceKey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get QrCode. Returns the qrcode in the base64 format.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyQrcodeGetWithHttpInfo (string instanceKey)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyQrcodeGet");

            var localVarPath = "/instances/{instance_key}/qrcode";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyQrcodeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get QrCode. Returns the qrcode in the base64 format.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyQrcodeGetAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyQrcodeGetWithHttpInfoAsync(instanceKey, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get QrCode. Returns the qrcode in the base64 format.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyQrcodeGetWithHttpInfoAsync (string instanceKey, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyQrcodeGet");

            var localVarPath = "/instances/{instance_key}/qrcode";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyQrcodeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Change Webhook url. Changes the webhook url of an instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesInstanceKeyWebhookPut (string instanceKey, StructsWebhookPayload data)
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesInstanceKeyWebhookPutWithHttpInfo(instanceKey, data);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Change Webhook url. Changes the webhook url of an instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesInstanceKeyWebhookPutWithHttpInfo (string instanceKey, StructsWebhookPayload data)
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyWebhookPut");
            // verify the required parameter 'data' is set
            if (data == null)
                throw new ApiException(400, "Missing required parameter 'data' when calling InstanceApi->InstancesInstanceKeyWebhookPut");

            var localVarPath = "/instances/{instance_key}/webhook";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyWebhookPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Change Webhook url. Changes the webhook url of an instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesInstanceKeyWebhookPutAsync (string instanceKey, StructsWebhookPayload data, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesInstanceKeyWebhookPutWithHttpInfoAsync(instanceKey, data, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Change Webhook url. Changes the webhook url of an instance.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instanceKey">Instance key</param>
        /// <param name="data">Message data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesInstanceKeyWebhookPutWithHttpInfoAsync (string instanceKey, StructsWebhookPayload data, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'instanceKey' is set
            if (instanceKey == null)
                throw new ApiException(400, "Missing required parameter 'instanceKey' when calling InstanceApi->InstancesInstanceKeyWebhookPut");
            // verify the required parameter 'data' is set
            if (data == null)
                throw new ApiException(400, "Missing required parameter 'data' when calling InstanceApi->InstancesInstanceKeyWebhookPut");

            var localVarPath = "/instances/{instance_key}/webhook";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instanceKey != null) localVarPathParams.Add("instance_key", this.Configuration.ApiClient.ParameterToString(instanceKey)); // path parameter
            if (data != null && data.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(data); // http body (model) parameter
            }
            else
            {
                localVarPostBody = data; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesInstanceKeyWebhookPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get all instances. Fetches the list of all Instances with login status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MainAPIResponse</returns>
        public MainAPIResponse InstancesListGet ()
        {
             ApiResponse<MainAPIResponse> localVarResponse = InstancesListGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all instances. Fetches the list of all Instances with login status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MainAPIResponse</returns>
        public ApiResponse<MainAPIResponse> InstancesListGetWithHttpInfo ()
        {

            var localVarPath = "/instances/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

        /// <summary>
        /// Get all instances. Fetches the list of all Instances with login status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of MainAPIResponse</returns>
        public async System.Threading.Tasks.Task<MainAPIResponse> InstancesListGetAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<MainAPIResponse> localVarResponse = await InstancesListGetWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all instances. Fetches the list of all Instances with login status.
        /// </summary>
        /// <exception cref="WhatsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (MainAPIResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MainAPIResponse>> InstancesListGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/instances/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("InstancesListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MainAPIResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MainAPIResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MainAPIResponse)));
        }

    }
}
