/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using whatsapi.Api;
using whatsapi.Model;
using whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace whatsapi.Test
{
    /// <summary>
    ///  Class for testing InstancesInstanceKeySendDocumentPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstancesInstanceKeySendDocumentPostRequestTests
    {
        // TODO uncomment below to declare an instance variable for InstancesInstanceKeySendDocumentPostRequest
        //private InstancesInstanceKeySendDocumentPostRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstancesInstanceKeySendDocumentPostRequest
            //instance = new InstancesInstanceKeySendDocumentPostRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstancesInstanceKeySendDocumentPostRequest
        /// </summary>
        [Test]
        public void InstancesInstanceKeySendDocumentPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InstancesInstanceKeySendDocumentPostRequest
            //Assert.IsInstanceOf(typeof(InstancesInstanceKeySendDocumentPostRequest), instance);
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
