/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using whatsapi.Api;
using whatsapi.Model;
using whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsTextMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsTextMessageTests
    {
        // TODO uncomment below to declare an instance variable for StructsTextMessage
        //private StructsTextMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsTextMessage
            //instance = new StructsTextMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsTextMessage
        /// </summary>
        [Test]
        public void StructsTextMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsTextMessage
            //Assert.IsInstanceOf(typeof(StructsTextMessage), instance);
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
