/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using whatsapi.Api;
using whatsapi.Model;
using whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsListItemTests
    {
        // TODO uncomment below to declare an instance variable for StructsListItem
        //private StructsListItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsListItem
            //instance = new StructsListItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsListItem
        /// </summary>
        [Test]
        public void StructsListItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsListItem
            //Assert.IsInstanceOf(typeof(StructsListItem), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'RowId'
        /// </summary>
        [Test]
        public void RowIdTest()
        {
            // TODO unit test for the property 'RowId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
