/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing GroupUpdateDescriptionPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupUpdateDescriptionPayloadTests
    {
        // TODO uncomment below to declare an instance variable for GroupUpdateDescriptionPayload
        //private GroupUpdateDescriptionPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupUpdateDescriptionPayload
            //instance = new GroupUpdateDescriptionPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupUpdateDescriptionPayload
        /// </summary>
        [Test]
        public void GroupUpdateDescriptionPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupUpdateDescriptionPayload
            //Assert.IsInstanceOf(typeof(GroupUpdateDescriptionPayload), instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
