/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing ListSection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListSectionTests
    {
        // TODO uncomment below to declare an instance variable for ListSection
        //private ListSection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListSection
            //instance = new ListSection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListSection
        /// </summary>
        [Test]
        public void ListSectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ListSection
            //Assert.IsInstanceOf(typeof(ListSection), instance);
        }


        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Test]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
