/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing ReplyButton
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplyButtonTests
    {
        // TODO uncomment below to declare an instance variable for ReplyButton
        //private ReplyButton instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplyButton
            //instance = new ReplyButton();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplyButton
        /// </summary>
        [Test]
        public void ReplyButtonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ReplyButton
            //Assert.IsInstanceOf(typeof(ReplyButton), instance);
        }


        /// <summary>
        /// Test the property 'ButtonId'
        /// </summary>
        [Test]
        public void ButtonIdTest()
        {
            // TODO unit test for the property 'ButtonId'
        }
        /// <summary>
        /// Test the property 'ButtonText'
        /// </summary>
        [Test]
        public void ButtonTextTest()
        {
            // TODO unit test for the property 'ButtonText'
        }

    }

}
