/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing SendVideoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendVideoRequestTests
    {
        // TODO uncomment below to declare an instance variable for SendVideoRequest
        //private SendVideoRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SendVideoRequest
            //instance = new SendVideoRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SendVideoRequest
        /// </summary>
        [Test]
        public void SendVideoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SendVideoRequest
            //Assert.IsInstanceOf(typeof(SendVideoRequest), instance);
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
