/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing StructsContactMessagePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsContactMessagePayloadTests
    {
        // TODO uncomment below to declare an instance variable for StructsContactMessagePayload
        //private StructsContactMessagePayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsContactMessagePayload
            //instance = new StructsContactMessagePayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsContactMessagePayload
        /// </summary>
        [Test]
        public void StructsContactMessagePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsContactMessagePayload
            //Assert.IsInstanceOf(typeof(StructsContactMessagePayload), instance);
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Vcard'
        /// </summary>
        [Test]
        public void VcardTest()
        {
            // TODO unit test for the property 'Vcard'
        }

    }

}
