/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing TemplateButton
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateButtonTests
    {
        // TODO uncomment below to declare an instance variable for TemplateButton
        //private TemplateButton instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateButton
            //instance = new TemplateButton();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateButton
        /// </summary>
        [Test]
        public void TemplateButtonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TemplateButton
            //Assert.IsInstanceOf(typeof(TemplateButton), instance);
        }


        /// <summary>
        /// Test the property 'ButtonId'
        /// </summary>
        [Test]
        public void ButtonIdTest()
        {
            // TODO unit test for the property 'ButtonId'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Test]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
