/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WhatsAPI.whatsapi;
using WhatsAPI.models;
using WhatsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WhatsAPI.Test
{
    /// <summary>
    ///  Class for testing TemplateButtonPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateButtonPayloadTests
    {
        // TODO uncomment below to declare an instance variable for TemplateButtonPayload
        //private TemplateButtonPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TemplateButtonPayload
            //instance = new TemplateButtonPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateButtonPayload
        /// </summary>
        [Test]
        public void TemplateButtonPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TemplateButtonPayload
            //Assert.IsInstanceOf(typeof(TemplateButtonPayload), instance);
        }


        /// <summary>
        /// Test the property 'Buttons'
        /// </summary>
        [Test]
        public void ButtonsTest()
        {
            // TODO unit test for the property 'Buttons'
        }
        /// <summary>
        /// Test the property 'ContentText'
        /// </summary>
        [Test]
        public void ContentTextTest()
        {
            // TODO unit test for the property 'ContentText'
        }
        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Test]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
