/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WhatsAPI.Client.OpenAPIDateConverter;

namespace WhatsAPI.models
{
    /// <summary>
    /// CreateInstancePayload
    /// </summary>
    [DataContract]
    public partial class CreateInstancePayload :  IEquatable<CreateInstancePayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateInstancePayload" /> class.
        /// </summary>
        /// <param name="instanceKey">instanceKey.</param>
        /// <param name="webhookUrl">webhookUrl.</param>
        public CreateInstancePayload(string instanceKey = default(string), string webhookUrl = default(string))
        {
            this.InstanceKey = instanceKey;
            this.WebhookUrl = webhookUrl;
        }

        /// <summary>
        /// Gets or Sets InstanceKey
        /// </summary>
        [DataMember(Name="instance_key", EmitDefaultValue=false)]
        public string InstanceKey { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name="webhook_url", EmitDefaultValue=false)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateInstancePayload {\n");
            sb.Append("  InstanceKey: ").Append(InstanceKey).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateInstancePayload);
        }

        /// <summary>
        /// Returns true if CreateInstancePayload instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateInstancePayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateInstancePayload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InstanceKey == input.InstanceKey ||
                    (this.InstanceKey != null &&
                    this.InstanceKey.Equals(input.InstanceKey))
                ) && 
                (
                    this.WebhookUrl == input.WebhookUrl ||
                    (this.WebhookUrl != null &&
                    this.WebhookUrl.Equals(input.WebhookUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InstanceKey != null)
                    hashCode = hashCode * 59 + this.InstanceKey.GetHashCode();
                if (this.WebhookUrl != null)
                    hashCode = hashCode * 59 + this.WebhookUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
