/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using com.whatsapi.Client;
using com.whatsapi.Api;
using com.whatsapi.Model;

namespace com.whatsapi.Test
{
    /// <summary>
    ///  Class for testing MiscellaneousApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MiscellaneousApiTests
    {
        private MiscellaneousApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MiscellaneousApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MiscellaneousApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' MiscellaneousApi
            //Assert.IsInstanceOf(typeof(MiscellaneousApi), instance);
        }

        
        /// <summary>
        /// Test InstancesInstanceKeyMiscProfilePicGet
        /// </summary>
        [Test]
        public void InstancesInstanceKeyMiscProfilePicGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instanceKey = null;
            //string jid = null;
            //var response = instance.InstancesInstanceKeyMiscProfilePicGet(instanceKey, jid);
            //Assert.IsInstanceOf(typeof(MainAPIResponse), response, "response is MainAPIResponse");
        }
        
        /// <summary>
        /// Test InstancesInstanceKeyMiscUserInfoPost
        /// </summary>
        [Test]
        public void InstancesInstanceKeyMiscUserInfoPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instanceKey = null;
            //StructsUserInfoPayload data = null;
            //var response = instance.InstancesInstanceKeyMiscUserInfoPost(instanceKey, data);
            //Assert.IsInstanceOf(typeof(MainAPIResponse), response, "response is MainAPIResponse");
        }
        
    }

}
