/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.whatsapi.Api;
using com.whatsapi.Model;
using com.whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsFileUpload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsFileUploadTests
    {
        // TODO uncomment below to declare an instance variable for StructsFileUpload
        //private StructsFileUpload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsFileUpload
            //instance = new StructsFileUpload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsFileUpload
        /// </summary>
        [Test]
        public void StructsFileUploadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsFileUpload
            //Assert.IsInstanceOf(typeof(StructsFileUpload), instance);
        }


        /// <summary>
        /// Test the property 'DirectPath'
        /// </summary>
        [Test]
        public void DirectPathTest()
        {
            // TODO unit test for the property 'DirectPath'
        }
        /// <summary>
        /// Test the property 'FileEncSha256'
        /// </summary>
        [Test]
        public void FileEncSha256Test()
        {
            // TODO unit test for the property 'FileEncSha256'
        }
        /// <summary>
        /// Test the property 'FileLength'
        /// </summary>
        [Test]
        public void FileLengthTest()
        {
            // TODO unit test for the property 'FileLength'
        }
        /// <summary>
        /// Test the property 'FileSha256'
        /// </summary>
        [Test]
        public void FileSha256Test()
        {
            // TODO unit test for the property 'FileSha256'
        }
        /// <summary>
        /// Test the property 'MediaKey'
        /// </summary>
        [Test]
        public void MediaKeyTest()
        {
            // TODO unit test for the property 'MediaKey'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
