/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.whatsapi.Api;
using com.whatsapi.Model;
using com.whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsContactMessagePayloadVcard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsContactMessagePayloadVcardTests
    {
        // TODO uncomment below to declare an instance variable for StructsContactMessagePayloadVcard
        //private StructsContactMessagePayloadVcard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsContactMessagePayloadVcard
            //instance = new StructsContactMessagePayloadVcard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsContactMessagePayloadVcard
        /// </summary>
        [Test]
        public void StructsContactMessagePayloadVcardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsContactMessagePayloadVcard
            //Assert.IsInstanceOf(typeof(StructsContactMessagePayloadVcard), instance);
        }


        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Test]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

    }

}
