/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.whatsapi.Api;
using com.whatsapi.Model;
using com.whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsGroupCreatePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsGroupCreatePayloadTests
    {
        // TODO uncomment below to declare an instance variable for StructsGroupCreatePayload
        //private StructsGroupCreatePayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsGroupCreatePayload
            //instance = new StructsGroupCreatePayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsGroupCreatePayload
        /// </summary>
        [Test]
        public void StructsGroupCreatePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsGroupCreatePayload
            //Assert.IsInstanceOf(typeof(StructsGroupCreatePayload), instance);
        }


        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Test]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
        /// <summary>
        /// Test the property 'Participants'
        /// </summary>
        [Test]
        public void ParticipantsTest()
        {
            // TODO unit test for the property 'Participants'
        }

    }

}
