/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.whatsapi.Api;
using com.whatsapi.Model;
using com.whatsapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.whatsapi.Test
{
    /// <summary>
    ///  Class for testing StructsListSection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsListSectionTests
    {
        // TODO uncomment below to declare an instance variable for StructsListSection
        //private StructsListSection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsListSection
            //instance = new StructsListSection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsListSection
        /// </summary>
        [Test]
        public void StructsListSectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsListSection
            //Assert.IsInstanceOf(typeof(StructsListSection), instance);
        }


        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Test]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
