/*
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StructsButtonMessagePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StructsButtonMessagePayloadTests
    {
        // TODO uncomment below to declare an instance variable for StructsButtonMessagePayload
        //private StructsButtonMessagePayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StructsButtonMessagePayload
            //instance = new StructsButtonMessagePayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StructsButtonMessagePayload
        /// </summary>
        [Test]
        public void StructsButtonMessagePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StructsButtonMessagePayload
            //Assert.IsInstanceOf(typeof(StructsButtonMessagePayload), instance);
        }


        /// <summary>
        /// Test the property 'Buttons'
        /// </summary>
        [Test]
        public void ButtonsTest()
        {
            // TODO unit test for the property 'Buttons'
        }
        /// <summary>
        /// Test the property 'FooterText'
        /// </summary>
        [Test]
        public void FooterTextTest()
        {
            // TODO unit test for the property 'FooterText'
        }
        /// <summary>
        /// Test the property 'HeaderText'
        /// </summary>
        [Test]
        public void HeaderTextTest()
        {
            // TODO unit test for the property 'HeaderText'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
